coverage:
  precision: 2
  round: nearest
  range: "90...95"
  status:
    project:
      default: off
      tests:
        target: 90%
        paths: "tests/"
      app:
        target: 95%
        paths: "include/"
    patch:
      default: off
      tests:
        target: 95%
        paths: "tests/"
      app:
        target: 98%
        paths: "include/"

codecov:
  branch: master

comment:
  layout: "reach, diff, flags, files"
