stages:
  - cppcheck
  - run_example

variables:
  DOCKER_REGISTRY: registry.cn-hangzhou.aliyuncs.com/leosocy
  IMAGE: ${DOCKER_REGISTRY}/stp

# -------------------- Lints --------------------
cppcheck:
  stage: cppcheck
  image:
    name: ${DOCKER_REGISTRY}/cppcheck:1.83
  script:
    - cppcheck -j 4 --enable=warning,performance --error-exitcode=1 -I include example.cpp

# -------------------- Build Example --------------------
buildexample:
  stage: run_example
  image:
    name: ${IMAGE}:ci
  script:
    - mkdir -p exmaple_build; cd exmaple_build
    - g++ ../example.cpp -I../include --std=c++11 -o example && ./example
    